apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lookhin4181/nevers-kube-final:v1.0.20
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "1000m"
            memory: "1000Mi"
        env:
        - name: DATABASE_HOST
          value: mysql
        - name: DATABASE_PASSWORD
          value:  Pass1234
        - name: DATABASE_USER
          value: root
        - name: DATABASE_HOST
          value: mysql
        - name: DATABASE_PASSWORD
          value:  Pass1234
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_DBNAME
          value: mydb
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_BODYLIMIT
          value: "10M"
        - name: REDIS_MASTERNAME
          value: mymaster
        - name: REDIS_PASSWORD
          value: admin
        - name: REDIS_SENTINELADDRS
          value: sentinel-0.sentinel:5000,sentinel-1.sentinel:5000,sentinel-2.sentinel:5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080